name: 'Michael j Kinkade '
favicon: null
layout_spectrum: 0.9403866
typography_spectrum: 0.7975295
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#FFC67F'
    - '#997878'
    - '#5C4B43'
    - '#FFF3E0'
  brandStrength: 0.1875
  lightness: 0.7932331
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
