name: 'Michael j Kinkade '
favicon: null
layout_spectrum: 0.25423
typography_spectrum: 0.7975295
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080403'
    - '#3e2c44'
    - '#e1a6c6'
    - '#ffcea5'
    - '#8f6b9d'
  brandStrength: 0.4375
  lightness: 0.7932331
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
